### ISSUE TITLE
Integration of STM32G070CBT6 with M66 GSM Module- Reg

### ISSUE THREAD

**Issue by Jen-0** [kungfupizza/GSM-M66#1]
Currently I am planning to work with STM32G070CBT6. I went through the library developed by you for GSM module in accordance with Arduino ATMEGA2560. Now I need to know if the same library could be utilized for integration of STM32G070CBT6 with M66 Quectel (GSM Module). It would be great if you could help me with this. Looking forward to getting response from you.

--
Best Regards,
J J

**Comment by kungfupizza** [comment]
Hi,
I can make you this library at a cost. Contact me on my email: sarthak.kelapure@gmail.com

**Comment by kungfupizza** [comment]
No further information from the OP.
